
log: "log" # log file path
db: # database configuration
  username: "dev" # account username
  password: "dev#123456!" # account password
  dbname: "malle_video" # database name
  host: "192.168.0.160" # database host
  port: "3306" # database port
rule: # mysql banned explain fields' value
  selecttype: # mysql explain select_type banned values
    - "SUBQUERY"
    - "DERIVED"
    - "UNION"
    - "UNION RESULT"
  type: # mysql explain type banned values
    - "ALL"
  extra: # mysql explain type banned values
    - "Using filesort"
    - "Using temporary"